Task 3
ozoncp/ocp-experience-api pull request #4
Opened 2021-07-25 11:20 UTC by Instand

- add experience structure entity
- add functions to experience
- add file reading in loop
- add tests

2021-07-26 14:09 UTC, MrDniwe requested changes
Принципиальных проблем не вижу, мелочи фиксим и ок!

2021-07-26 14:09 UTC, MrDniwe commented on internal/utils/utils_test.go
> +const loopFileName = "/test_loop_file.txt"
```suggestion
const loopFileName = "./test_loop_file.txt"
```
В корне диска не очень хорошо файлы создавать)

2021-07-26 14:50 UTC, Instand commented on internal/utils/experience_utils.go
> +	}
Да, выглядит лучше, исправим

2021-07-26 14:52 UTC, Instand commented on internal/utils/experience_utils.go
> +	var entitiesSize = len(entities)
Понимаю и видел про :=, я не против :=, но код более читаемый, когда видно именно объявление переменной, т.е. var. Если это принципиально в Go, и есть конвенция использовать только := исправим, буду привыкать.

2021-07-26 14:53 UTC, Instand commented on internal/utils/utils_test.go
> +const loopFileName = "/test_loop_file.txt"
Это уже моя оЧепятка, собирался рядом с исполняемым файлом естественно, спасибо

2021-07-27 06:24 UTC, Instand commented on internal/utils/experience_utils.go
> +	var entitiesSize = len(entities)
Поправил во всем проекте, но, кажется, ухудшилась читаемость :)

2021-07-27 06:25 UTC, Instand commented on internal/utils/experience_utils.go
> +	var entitiesSize = len(entities)
Может и ок, просто с var более наглядно и сразу видно

2021-07-27 07:15 UTC, MrDniwe approved these changes

2021-07-27 07:24 UTC, merged